# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: dynamic-pvc
# spec:
#   storageClassName: standard   # important

#   accessModes:
#     - ReadWriteOnce

#   resources:
#     requests:
#       storage: 1Gi


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi