apiVersion: v1
kind: Pod
metadata:
  name: oom-demo
spec:
  containers:
  - name: memory-hog
    image: polinux/stress
    resources:
      limits:
        memory: "20Mi"
    command: ["stress"]
    args: ["--vm", "2", "--vm-bytes", "200M", "--vm-hang", "1"]